site_name: システム仕様書
use_directory_urls: false
theme:
  name: material
  language: ja
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - toc.follow

plugins:
  - search
  - i18n:
      languages:
        - locale: ja
          name: 日本語
          default: true
          build: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
  - pymdownx.superfences:
      custom_fences:
        - name: plantuml
          class: plantuml
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - 概要: 01-overview.md
  - システム構成: 02-system-architecture.md
  - 機能設計: 03-features.md
  - 画面設計: 04-screen-design.md
  - 運用設計: 05-operations.md
  - 付録: 06-appendix.md
